In [ ]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection.txt',
                    sep='\t',names=["label","message"])

In [ ]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [7]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

nltk
 ├── corpus
 │      └── stopwords
 ├── stem
 │      └── PorterStemmer
 ├── tokenize
 │      └── word_tokenize
 

In [8]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [ ]:
corpus

NameError: name 'corpus' is not defined

Excellent! This is the **most important code in Bag of Words (BoW)**. Interviewers frequently ask about it.

Let's understand **every line** in detail.

---

# Code

```python
from sklearn.feature_extraction.text import CountVectorizer

# For Binary Bag of Words
cv = CountVectorizer(max_features=100, binary=True)
```

---

# Line 1

```python
from sklearn.feature_extraction.text import CountVectorizer
```

## What is `sklearn`?

`sklearn` (Scikit-learn) is Python's Machine Learning library.

It provides:

* Linear Regression
* Decision Tree
* Random Forest
* SVM
* Bag of Words
* TF-IDF
* Feature Engineering

---

## What is `feature_extraction`?

Machine Learning cannot understand text.

It only understands:

```text
1
0
3.5
25
```

So we need to **extract features** (numerical values) from text.

That's why the module is called:

```text
feature_extraction
```

---

## What is `text`?

Inside `feature_extraction`, there are methods specifically for text.

Like:

* CountVectorizer
* TfidfVectorizer
* HashingVectorizer

---

## What is `CountVectorizer`?

It converts text into numbers by **counting how many times each word appears**.

---

# Example

Suppose we have two sentences.

```python
corpus = [
    "I love python",
    "I love machine learning"
]
```

Vocabulary becomes:

```text
I
love
python
machine
learning
```

Now CountVectorizer counts every word.

| Sentence                | I | love | python | machine | learning |
| ----------------------- | - | ---- | ------ | ------- | -------- |
| I love python           | 1 | 1    | 1      | 0       | 0        |
| I love machine learning | 1 | 1    | 0      | 1       | 1        |

This table is called the **Bag of Words matrix**.

---

# Line 2

```python
cv = CountVectorizer(max_features=100, binary=True)
```

Here we are **creating an object**.

Think of it like:

```python
car = Car()
```

Similarly,

```python
cv = CountVectorizer(...)
```

creates a CountVectorizer object.

---

# What is `max_features=100`?

Suppose your dataset contains

```text
50,000 unique words
```

Do you really need all of them?

Probably not.

Most words occur only once.

So we tell sklearn:

```python
max_features=100
```

Meaning

> Keep only the **100 most frequent words**.

---

## Example

Vocabulary

```text
apple
banana
car
python
machine
learning
deep
AI
...
```

Suppose frequencies are

| Word     | Frequency |
| -------- | --------- |
| the      | 9000      |
| is       | 8500      |
| python   | 6000      |
| AI       | 5500      |
| learning | 5200      |
| ...      | ...       |

If

```python
max_features=5
```

Only

```text
the
is
python
AI
learning
```

will be kept.

Everything else is ignored.

---

# Why use `max_features`?

Without it

```text
Vocabulary = 100,000 words
```

Matrix becomes

```text
5000 × 100000
```

Huge!

Training becomes slower.

Using

```python
max_features=1000
```

keeps only important words.

---

# What is `binary=True`?

Normally CountVectorizer stores **word counts**.

Example

Sentence

```text
I love love love Python
```

Normal CountVectorizer

| I | love | python |
| - | ---- | ------ |
| 1 | 3    | 1      |

because

```text
love
```

appears

```text
3 times
```

---

With

```python
binary=True
```

it stores only

> Did the word appear?

YES → 1

NO → 0

So

| I | love | python |
| - | ---- | ------ |
| 1 | 1    | 1      |

Notice

```text
love
```

appeared 3 times

Still

```text
1
```

because we only care about presence.

---

# Difference

## Normal Bag of Words

Sentence

```text
Python Python Python AI
```

Vector

```text
Python = 3
AI = 1
```

---

## Binary Bag of Words

Sentence

```text
Python Python Python AI
```

Vector

```text
Python = 1
AI = 1
```

Only presence matters.

---

# When do we use Binary Bag of Words?

Good for

* Spam Detection
* Email Classification
* Fake News Detection

Sometimes knowing

> Word exists

is more useful than

> Word appears 15 times.

---

# After creating `cv`

You usually write

```python
X = cv.fit_transform(corpus)
```

Suppose

```python
corpus = [
    "I love python",
    "I love AI"
]
```

Vocabulary

```text
I
love
python
AI
```

Output

| Sentence      | I | love | python | AI |
| ------------- | - | ---- | ------ | -- |
| I love python | 1 | 1    | 1      | 0  |
| I love AI     | 1 | 1    | 0      | 1  |

This is the numerical matrix used by the Machine Learning model.

---

# Interview Questions

### Q1. What is CountVectorizer?

**Answer:**
CountVectorizer converts text into numerical vectors by counting the occurrence of words in a document. It is used to create a Bag of Words representation.

---

### Q2. What is `max_features`?

**Answer:**
It limits the vocabulary to the most frequent words. This reduces dimensionality, memory usage, and training time.

---

### Q3. What is `binary=True`?

**Answer:**
Instead of storing the number of occurrences of a word, it stores only whether the word is present (`1`) or absent (`0`).

---

## Flow of the Entire BoW Pipeline

```text
Raw SMS Messages
        │
        ▼
Text Preprocessing
(Tokenize, Lowercase, Remove Stopwords, Stemming)
        │
        ▼
Clean Corpus
        │
        ▼
CountVectorizer
        │
        ▼
Bag of Words Matrix (Numbers)
        │
        ▼
Machine Learning Model
(Logistic Regression, Naive Bayes, SVM, etc.)
```

This is the standard workflow you'll use in most classical NLP projects before training a machine learning classifier.


In [ ]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:

from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=100,binary=True)

In [ ]:
X=cv.fit_transform(corpus).toarray()

NameError: name 'corpus' is not defined

Excellent question. **The answer is NO.** This is a very common interview trick.

## Short Answer

❌ `fit_transform()` **does not train the Machine Learning model.**

It **trains the vectorizer** (or preprocessor), **not the ML model**.

---

# Think of the Complete ML Pipeline

Imagine you are building a Spam Detection model.

### Step 1: Raw Text

```text
"I love Python"

"Win $1000 now"

"Congratulations! You won"
```

Machine Learning **cannot understand text**.

---

### Step 2: CountVectorizer

```python
cv = CountVectorizer()
X = cv.fit_transform(corpus)
```

Here,

```text
fit()
```

means:

> Learn the vocabulary (dictionary of words).

Example:

```text
I
love
Python
Win
Congratulations
won
```

Then,

```text
transform()
```

converts the sentences into numbers.

For example:

| Sentence      | I | love | Python | Win |
| ------------- | - | ---- | ------ | --- |
| I love Python | 1 | 1    | 1      | 0   |
| Win $1000     | 0 | 0    | 0      | 1   |

So after `fit_transform()`, you only have **numerical features**.

---

### Step 3: Train the ML Model

Now you train the actual model.

```python
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X, y)
```

Here,

```python
model.fit(X, y)
```

**This is the actual training step.**

The model learns:

* Which words indicate spam.
* Which words indicate ham (not spam).

---

# Visual Flow

```text
Raw Text
     │
     ▼
CountVectorizer.fit_transform()
     │
     ▼
Numbers (Feature Matrix X)
     │
     ▼
Machine Learning Model
(model.fit(X, y))
     │
     ▼
Trained Model
```

---

# Why is `fit()` used in CountVectorizer?

Because CountVectorizer also has something to learn.

For example:

```python
corpus = [
    "I love Python",
    "I love AI"
]
```

During

```python
cv.fit(corpus)
```

it learns:

```python
{
'AI':0,
'I':1,
'Python':2,
'love':3
}
```

This vocabulary is stored inside the vectorizer.

So **the vectorizer is "trained" to understand the words**, but **it is not making predictions**.

---

# Compare Both `fit()` Methods

### CountVectorizer

```python
cv.fit(corpus)
```

Learns:

✅ Vocabulary

Output:

```text
Word → Index
```

---

### Machine Learning Model

```python
model.fit(X, y)
```

Learns:

✅ Relationship between features (X) and target labels (y)

Output:

```text
Spam or Not Spam
```

---

# Real-Life Analogy

Imagine you are teaching a child.

### Step 1

Teach the alphabet.

```text
A
B
C
D
```

This is like:

```python
CountVectorizer.fit()
```

The child is **learning the alphabet**, not solving problems yet.

---

### Step 2

Teach the child to solve math problems.

```text
2 + 2 = 4
```

This is like:

```python
model.fit()
```

Now the child is learning how to make decisions.

---

# Interview Question

### Q: Does `CountVectorizer.fit_transform()` train the machine learning model?

**Answer:**

**No.** It only learns the vocabulary and converts text into numerical vectors. The actual machine learning model is trained later using `model.fit(X, y)`.

---

## Memory Trick

```
CountVectorizer.fit()
        ↓
Learns Words (Vocabulary)

CountVectorizer.transform()
        ↓
Converts Text → Numbers

model.fit()
        ↓
Learns Numbers → Prediction
```

### One sentence to remember forever:

* **`CountVectorizer.fit_transform()` = Train the text preprocessor (learn vocabulary).**
* **`model.fit()` = Train the machine learning model (learn patterns for prediction).**

This distinction is one of the most frequently asked concepts in NLP and Scikit-learn interviews.




In [ ]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))

Excellent! This code is commonly used in **NumPy** to make arrays easier to read, especially when working with **Machine Learning**, **NLP**, and **Deep Learning**.

Let's understand **every line**.

---

# Code

```python
import numpy as np

np.set_printoptions(
    edgeitems=30,
    linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x)
)
```

---

# Line 1

```python
import numpy as np
```

### Meaning

Import the NumPy library.

`np` is just a shortcut.

Instead of writing

```python
numpy.array()
```

we write

```python
np.array()
```

---

# Line 2

```python
np.set_printoptions(...)
```

### What does it do?

It changes **how NumPy prints arrays**.

It **does not change the actual data**.

Think of it like changing the font size on your phone.

The photo remains the same; only how you view it changes.

---

## Example

Without `set_printoptions`

```python
import numpy as np

arr = np.arange(100)

print(arr)
```

Output

```text
[ 0  1  2 ... 97 98 99]
```

NumPy hides the middle values using `...`.

---

After

```python
np.set_printoptions(edgeitems=30)
```

Output

```text
[ 0 1 2 3 4 5 6 7 8 ... 91 92 93 94 95 96 97 98 99]
```

It prints more values from the beginning and end.

---

# Parameter 1

```python
edgeitems=30
```

## Meaning

When NumPy shortens a large array,

show

* first **30**
* last **30**

instead of only a few.

---

Example

Array

```python
arr = np.arange(100)
```

Normally

```text
[0 1 2 ... 97 98 99]
```

With

```python
edgeitems=10
```

Output

```text
[0 1 2 3 4 5 6 7 8 9 ... 90 91 92 93 94 95 96 97 98 99]
```

---

# Parameter 2

```python
linewidth=100000
```

## Meaning

Maximum number of characters on one line before NumPy wraps to the next line.

---

Without it

```text
[1 2 3 4 5
 6 7 8 9]
```

The array is broken into multiple lines.

---

With

```python
linewidth=100000
```

Output

```text
[1 2 3 4 5 6 7 8 9]
```

Everything stays on one line.

---

## Why use it?

Very useful in

* NLP
* Machine Learning
* Deep Learning

because vectors may contain hundreds of values.

---

# Parameter 3

```python
formatter=dict(...)
```

## Meaning

Tell NumPy **how to display numbers**.

---

Inside it

```python
formatter=dict(float=lambda x: "%.3g" % x)
```

This means

> Every float should be printed using this function.

---

## What is `lambda`?

A lambda is an **anonymous (one-line) function**.

Instead of writing

```python
def format_number(x):
    return "%.3g" % x
```

we write

```python
lambda x: "%.3g" % x
```

Both do the same thing.

---

# What is `"%.3g"`?

This is an old-style Python formatting string.

`g` = General format (uses fixed-point or scientific notation depending on the number).

`.3` = Show **3 significant digits**.

---

## Example

```python
x = 123.456789
```

Normal print

```text
123.456789
```

With

```python
"%.3g" % x
```

Output

```text
123
```

---

Another example

```python
x = 0.000123456
```

Output

```text
0.000123
```

---

Large number

```python
x = 123456789
```

Output

```text
1.23e+08
```

---

# Complete Example

```python
import numpy as np

arr = np.array([
    12.3456789,
    1234567.89,
    0.000012345
])

print(arr)
```

Without formatting

```text
[1.23456789e+01 1.23456789e+06 1.23450000e-05]
```

Hard to read.

---

Now

```python
np.set_printoptions(
    formatter={'float': lambda x: "%.3g" % x}
)

print(arr)
```

Output

```text
[12.3 1.23e+06 1.23e-05]
```

Much cleaner.

---

# Why is this useful in NLP?

Suppose you create a Bag of Words matrix.

```python
X = cv.fit_transform(corpus).toarray()
```

The matrix might have **thousands of values**.

Without `set_printoptions()`

```text
[[0 1 0 ... 1 0 0]
 ...
]
```

or values may wrap across many lines.

With these print options:

* More of the array is visible (`edgeitems`)
* It stays on one line (`linewidth`)
* Floating-point numbers are shorter and easier to read (`formatter`)

---

# Interview Questions

### Q1. What does `np.set_printoptions()` do?

**Answer:**
It changes how NumPy arrays are **displayed** when printed. It does **not** change the underlying data.

---

### Q2. What is `edgeitems`?

**Answer:**
It specifies how many elements from the beginning and end of a large array should be shown before NumPy uses `...`.

---

### Q3. What is `linewidth`?

**Answer:**
It sets the maximum number of characters per line before NumPy wraps the output to a new line.

---

### Q4. What does `formatter` do?

**Answer:**
It customizes how different data types (such as floats) are displayed when printed.

---

## Memory Trick

```
np.set_printoptions()

edgeitems  → Show more values at the beginning and end
linewidth  → Keep output on one line
formatter  → Change how numbers look when printed
```

The important thing to remember is that these options affect **only the display**, not the actual NumPy array stored in memory.


In [ ]:
## Create the Bag OF Words model with ngram
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=100,binary=True,ngram_range=(2,3))
X=cv.fit_transform(corpus).toarray()

In [ ]:
cv.vocabulary_


In [ ]:
X

This is one of the **most important NLP concepts**. Your screenshot is explaining **N-Grams** in **Bag of Words**.

Many students get confused here, so let's build it from scratch.

---

# Step 1: Problem with Normal Bag of Words (Unigram)

Suppose we have two sentences:

```text
S1 = The food is good
S2 = The food is not good
```

After preprocessing (remove stopwords like "the", "is"):

```text
S1 = food good
S2 = food not good
```

Vocabulary becomes:

```text
food
not
good
```

BoW matrix:

| Sentence | food | not | good |
| -------- | ---- | --- | ---- |
| S1       | 1    | 0   | 1    |
| S2       | 1    | 1   | 1    |

Notice something?

Both sentences look **almost the same**.

The only difference is:

```text
not
```

But in reality,

```text
food good
```

means **positive** 😊

while

```text
food not good
```

means **negative** 😞

The normal Bag of Words cannot understand that **"not good"** is a phrase.

---

# Step 2: Solution → N-Grams

Instead of looking at **one word**, look at **multiple consecutive words**.

---

## Unigram (1 word)

Sentence

```text
food not good
```

Tokens:

```text
food
not
good
```

These are called **Unigrams**.

---

## Bigram (2 words)

Now combine every two consecutive words.

Sentence

```text
food not good
```

Becomes

```text
food not
not good
```

These are called **Bigrams**.

Notice:

```text
not good
```

is now treated as a **single feature**.

Now the model can understand

```text
not good
```

has a different meaning than

```text
good
```

---

# Your Screenshot

Vocabulary becomes

```text
food
not
good
food good
food not
not good
```

Let's create the table.

### Sentence 1

```text
food good
```

Contains

✅ food

❌ not

✅ good

✅ food good

❌ food not

❌ not good

So

| food | not | good | food good | food not | not good |
| ---- | --- | ---- | --------- | -------- | -------- |
| 1    | 0   | 1    | 1         | 0        | 0        |

---

### Sentence 2

```text
food not good
```

Contains

✅ food

✅ not

✅ good

❌ food good

✅ food not

✅ not good

So

| food | not | good | food good | food not | not good |
| ---- | --- | ---- | --------- | -------- | -------- |
| 1    | 1   | 1    | 0         | 1        | 1        |

Now the model can clearly distinguish between the two sentences.

---

# Why Bigram is Better?

Without bigrams

```text
good
not
```

are treated separately.

With bigrams

```text
not good
```

becomes a **single feature**.

This preserves some context.

---

# What is N in N-Gram?

N means **how many consecutive words are grouped together**.

### Unigram (N=1)

```text
I
love
Python
```

---

### Bigram (N=2)

```text
I love
love Python
```

---

### Trigram (N=3)

```text
I love Python
```

---

### Four-gram (N=4)

Sentence

```text
I love learning Python
```

becomes

```text
I love learning Python
```

---

# In Scikit-learn

### Only Unigrams

```python
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(1,1))
```

Output

```text
food
good
not
```

---

### Only Bigrams

```python
cv = CountVectorizer(ngram_range=(2,2))
```

Output

```text
food good
food not
not good
```

---

### Unigram + Bigram

```python
cv = CountVectorizer(ngram_range=(1,2))
```

Output

```text
food
good
not
food good
food not
not good
```

This is what your screenshot shows.

---

### Unigram + Bigram + Trigram

```python
cv = CountVectorizer(ngram_range=(1,3))
```

Output

```text
food
good
not

food good
food not
not good

food not good
```

---

# Why not always use Trigram or 4-Gram?

Because the vocabulary grows very quickly.

Example:

Suppose you have

```text
10,000 unique words
```

Unigrams:

```
10,000 features
```

Unigrams + Bigrams:

```
Hundreds of thousands of features
```

Unigrams + Bigrams + Trigrams:

```
Millions of features
```

This makes training slower and uses much more memory.

---

# When to use which?

### Unigram `(1,1)`

✅ Small datasets

✅ Simple text classification

---

### Unigram + Bigram `(1,2)` ⭐

Most commonly used.

Captures phrases like

```text
not good
very happy
machine learning
```

---

### Unigram + Bigram + Trigram `(1,3)`

Useful when phrases of three words matter, such as:

```text
New York City
United States Government
I love Python
```

---

# Real-Life Analogy

Imagine reading this sentence:

```text
I am not happy
```

### Unigram

You see

```text
I
am
not
happy
```

The model sees "happy" and may think the sentence is positive.

### Bigram

You also see

```text
not happy
```

Now the model understands the negative meaning.

---

# Interview Questions

### Q1. What is an N-Gram?

**Answer:**
An N-Gram is a sequence of **N consecutive words** extracted from a sentence.

---

### Q2. Why do we use Bigrams?

**Answer:**
Bigrams preserve local context by treating two consecutive words (such as "not good") as a single feature, which helps capture meaning that unigrams may miss.

---

### Q3. What does `ngram_range=(1,2)` mean?

**Answer:**
It includes both unigrams (single words) and bigrams (pairs of consecutive words).

---

# Memory Trick

```
Sentence:
I love Machine Learning

Unigram (1)
↓
I
love
Machine
Learning

Bigram (2)
↓
I love
love Machine
Machine Learning

Trigram (3)
↓
I love Machine
love Machine Learning
```

## Rule to remember

* **Unigram** → One word (less context, fewer features)
* **Bigram** → Two words (captures short phrases like *not good*)
* **Trigram** → Three words (captures longer expressions)
* Increasing **N** gives **more context** but also **more features**, which increases memory usage and training time.
